### PR TITLE
Pm ghpages branch

### PR DESCRIPTION
**Pull request by PatrickWMartin**
Adding in all my episodes. Most are in a decent place but detection loading needs a lot of work adding more substance to it. The other ones need mostly just editing but any addtional content thought would be great.

### CODE REVIEW

**Comment by CaitlinBate** [comment]
note to self: need to finish detections lesson and Push lesson (bottom parts of them)

**Comment by CaitlinBate** [comment]
actual note: we need to link to angela's nice ER / path-of-date diagram in ep02

**Review by CaitlinBate — APPROVED** [review]
Done my editing of these - we can get more eyes on them later

**Comment by jdpye** [comment]
I tried to make the the text of the first couple episodes more directly geared towards incoming node managers. If there are places where i missed the mark on that please continue to revise the language with the new folks in mind.

**Review by jdpye — APPROVED** [review]

**Pull request merged**
