### PR TITLE
first bash at ep05 - no spellcheck yet (sorry)

### PR DESCRIPTION
**Pull request by CaitlinBate**
things that need review:

- adding sci-name section
- loading using a link to file section
- all the spelling :)

### CODE REVIEW

**Comment by CaitlinBate** [comment]
new commit with some spellchecking done

**Comment by naomitress** [comment]
@CaitlinBate would you consider splitting the plone section into its own lesson, and maybe we can interview joy for content about RW?

**Review by naomitress — APPROVED** [review]

**Comment by CaitlinBate** [comment]
> @CaitlinBate would you consider splitting the plone section into its own lesson, and maybe we can interview joy for content about RW?

If we were to talk about RW we would also have to talk about whatever ACT uses, etc. Neither of which have their own Notebooks to reference?

I like the idea of pulling Plone-creation out somehow. Or at least adding a VERY clear break in the lesson stating 'many nodes use other things, but if you use Plone here's the steps to finish Project Metadata'. I can look into markdown formatting options

**Comment by CaitlinBate** [comment]
new commits here:

1) formatting changes to the Plone section of ep05
2) first bash at ep06 - tag metadata

**Review by naomitress — APPROVED** [review]

**Review by naomitress — APPROVED** [review]

**Review by PatrickWMartin — APPROVED** [review]

**Pull request merged**
